services:
    node:
        build:
            context: app
            dockerfile: Dockerfile
        environment:
            - PORT=3000
            - DICTIONARY_API=https://api.dictionaryapi.dev/api/v2/entries/en/
            - SPACEFLIGHT_NEWS_API=https://api.spaceflightnewsapi.net/v4/articles/
            - QUOTES_API=https://api.quotable.io/random
            - REDIS_URI=redis://redis:6379
        command: npm start
        volumes:
            - ./app:/app
        deploy:
            replicas: 5
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
            interval: 3s
            timeout: 1s
            retries: 5
    nginx:
        image: nginx:1.25.4
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        depends_on:
            node:
                condition: service_healthy

    redis:
      image: redis:7.4.0
      ports:
        - "6379:6379"

    graphite:
        image: graphiteapp/graphite-statsd:1.1.10-5
        volumes:
            - ./statsd.config.js:/opt/statsd/config/udp.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:10.1.9
        ports:
            - "80:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.49.1
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s" --docker_only=true
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

volumes:
    grafana_config:
        driver: local
