services:
    node:
        build:
            context: app
            dockerfile: Dockerfile
        depends_on: 
            - redis
            - graphite
        environment:
            - PORT=3000
            - DICTIONARY_API=https://api.dictionaryapi.dev/api/v2/entries/en/
            - SPACEFLIGHT_NEWS_API=https://api.spaceflightnewsapi.net/v4/articles/
            - QUOTES_API=https://api.quotable.io/random
            - REDIS_URI=redis://redis:6379
            - USE_CACHE=${USE_CACHE-no}
        volumes:
            - ./app/index.js:/app/index.js
            - ./app/redis.js:/app/redis.js
        command: npm start
        deploy:
            replicas: 5
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        ports:
            - "5555:80"
        volumes:
            #- ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        environment:
            - RATE_LIMIT=${RATE_LIMIT-999999r/s}
        depends_on:
            - node

    redis:
      image: redis:7.4.0
      ports:
        - "6379:6379"

    graphite:
        image: graphiteapp/graphite-statsd:1.1.10-5
        volumes:
            - ./statsd.config.js:/opt/statsd/config/udp.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"
            - "2003:2003"

    grafana:
        image: grafana/grafana:11.2.2
        ports:
            - "80:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.49.1
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s" --docker_only=true
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

volumes:
    grafana_config:
        driver: local

networks:
    default:
        name: 7543-arquitectura-software